# Generated by Django 3.2.13 on 2022-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('py', 'python'), ('c', 'ANSI_C')], max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='style',
            field=models.CharField(choices=[('f', 'friendly'), ('h', 'hostile')], default='f', max_length=100),
        ),
    ]
