# Generated by Django 3.2.13 on 2022-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='banaananana',
            field=models.CharField(default='null', max_length=420),
        ),
    ]
