# Generated by Django 3.2.13 on 2022-04-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='banaananana',
        ),
    ]
