# Generated by Django 3.2.13 on 2022-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_banaananana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
    ]
