# Generated by Django 3.2.13 on 2022-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='tasty',
            field=models.BooleanField(default=True),
        ),
    ]
