# Generated by Django 3.2.13 on 2022-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Manufactured time')),
                ('brand', models.CharField(max_length=20)),
                ('price', models.FloatField(default=69.99, max_length=20)),
            ],
        ),
    ]
