# Generated by Django 3.2.13 on 2022-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
