# Generated by Django 3.2.13 on 2022-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acccount_type',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
