# Generated by Django 3.2.13 on 2022-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_user_acccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
