# Generated by Django 3.2.13 on 2022-04-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acccount_type',
            new_name='account_type',
        ),
    ]
